#这里目前还缺少矩形键盘按键，LED（如果有的话），VGA的引脚约束，如果你们改了的话把这行注释删了
set_property PACKAGE_PIN M24 [get_ports SEGCLK]
set_property PACKAGE_PIN M20 [get_ports SEGCLR]
set_property PACKAGE_PIN L24 [get_ports SEGDT]
set_property PACKAGE_PIN R18 [get_ports SEGEN]
set_property IOSTANDARD LVCMOS33 [get_ports SEGCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SEGCLR]
set_property IOSTANDARD LVCMOS33 [get_ports SEGDT]
set_property IOSTANDARD LVCMOS33 [get_ports SEGEN]
set_property PACKAGE_PIN AC18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
create_clock -period 10.000 -name clk [get_ports "clk"]
set_property PACKAGE_PIN AA10 [get_ports {S1}]
set_property IOSTANDARD LVCMOS15 [get_ports {S1}]
set_property PACKAGE_PIN AB10 [get_ports {S2}]
set_property IOSTANDARD LVCMOS15 [get_ports {S2}]
set_property PACKAGE_PIN AA13 [get_ports {S3}]
set_property IOSTANDARD LVCMOS15 [get_ports {S3}]
set_property PACKAGE_PIN AA12 [get_ports {S4}]
set_property IOSTANDARD LVCMOS15 [get_ports {S4}]
set_property PACKAGE_PIN Y13 [get_ports {S5}]
set_property IOSTANDARD LVCMOS15 [get_ports {S5}]
set_property PACKAGE_PIN AF25 [get_ports buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]
# set_property PACKAGE_PIN V17 [get_ports btnx[0]]
# set_property IOSTANDARD LVCMOS18 [get_ports btnx[0]]
# set_property PACKAGE_PIN W18 [get_ports btnx[1]]
# set_property IOSTANDARD LVCMOS18 [get_ports btnx[1]]
# set_property PACKAGE_PIN W19 [get_ports btnx[2]]
# set_property IOSTANDARD LVCMOS18 [get_ports btnx[2]]
# set_property PACKAGE_PIN V18 [get_ports btn[0]]
# set_property IOSTANDARD LVCMOS18 [get_ports btn[0]]
# set_property PACKAGE_PIN V19 [get_ports btn[1]]
# set_property IOSTANDARD LVCMOS18 [get_ports btn[1]]
# set_property PACKAGE_PIN V14 [get_ports btn[0]]
# set_property IOSTANDARD LVCMOS18 [get_ports btn[0]]
#矩形键盘，我不会绑了我去。
