set_property SRC_FILE_INFO {cfile:f:/LDFEXP/2024Final/2024Final.gen/sources_1/ip/blk_mem_num_font/blk_mem_num_font/blk_mem_num_font_in_context.xdc rfile:../../../../../2024Final.gen/sources_1/ip/blk_mem_num_font/blk_mem_num_font/blk_mem_num_font_in_context.xdc id:1 order:EARLY scoped_inst:page_config_inst/font_data} [current_design]
set_property SRC_FILE_INFO {cfile:f:/LDFEXP/2024Final/2024Final.gen/sources_1/ip/blk_mem_num_font/blk_mem_num_font/blk_mem_num_font_in_context.xdc rfile:../../../../../2024Final.gen/sources_1/ip/blk_mem_num_font/blk_mem_num_font/blk_mem_num_font_in_context.xdc id:2 order:EARLY scoped_inst:page_game_inst/font_data} [current_design]
set_property SRC_FILE_INFO {cfile:f:/LDFEXP/2024Final/2024Final.gen/sources_1/ip/blk_mem_main_menu/blk_mem_main_menu/blk_mem_main_menu_in_context.xdc rfile:../../../../../2024Final.gen/sources_1/ip/blk_mem_main_menu/blk_mem_main_menu/blk_mem_main_menu_in_context.xdc id:3 order:EARLY scoped_inst:page_main_inst/main_menu_data} [current_design]
set_property SRC_FILE_INFO {cfile:f:/LDFEXP/2024Final/2024Final.gen/sources_1/ip/blk_mem_help_menu/blk_mem_help_menu/blk_mem_help_menu_in_context.xdc rfile:../../../../../2024Final.gen/sources_1/ip/blk_mem_help_menu/blk_mem_help_menu/blk_mem_help_menu_in_context.xdc id:4 order:EARLY scoped_inst:page_help_inst/help_menu_data} [current_design]
set_property SRC_FILE_INFO {cfile:f:/LDFEXP/2024Final/2024Final.gen/sources_1/ip/blk_mem_config_menu/blk_mem_config_menu/blk_mem_config_menu_in_context.xdc rfile:../../../../../2024Final.gen/sources_1/ip/blk_mem_config_menu/blk_mem_config_menu/blk_mem_config_menu_in_context.xdc id:5 order:EARLY scoped_inst:page_config_inst/config_menu_data} [current_design]
set_property SRC_FILE_INFO {cfile:F:/LDFEXP/2024Final/VGA/vga_test_top.xdc rfile:../../../../../VGA/vga_test_top.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:F:/LDFEXP/2024Final/pages/page_debug_top.xdc rfile:../../../../../pages/page_debug_top.xdc id:7} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins page_config_inst/font_data/clka]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells page_config_inst/font_data]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins page_game_inst/font_data/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells page_game_inst/font_data]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins page_main_inst/main_menu_data/clka]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells page_main_inst/main_menu_data]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins page_help_inst/help_menu_data/clka]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells page_help_inst/help_menu_data]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins page_config_inst/config_menu_data/clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells page_config_inst/config_menu_data]
set_property src_info {type:XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk [get_ports sys_clk]
set_property src_info {type:XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk [get_ports sys_clk]
set_property src_info {type:XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports sys_clk]
set_property src_info {type:XDC file:7 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_clk]
set_property src_info {type:XDC file:7 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_data]
set_property src_info {type:XDC file:7 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[0]}]
set_property src_info {type:XDC file:7 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[1]}]
set_property src_info {type:XDC file:7 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[2]}]
set_property src_info {type:XDC file:7 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[3]}]
set_property src_info {type:XDC file:7 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[4]}]
set_property src_info {type:XDC file:7 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[5]}]
set_property src_info {type:XDC file:7 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[6]}]
set_property src_info {type:XDC file:7 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[7]}]
set_property src_info {type:XDC file:7 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[8]}]
set_property src_info {type:XDC file:7 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[9]}]
set_property src_info {type:XDC file:7 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[10]}]
set_property src_info {type:XDC file:7 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {pixel_data[11]}]
set_property src_info {type:XDC file:7 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync]
set_property src_info {type:XDC file:7 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync]
set_property src_info {type:XDC file:7 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[0]}]
set_property src_info {type:XDC file:7 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[1]}]
set_property src_info {type:XDC file:7 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[2]}]
set_property src_info {type:XDC file:7 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[3]}]
set_property src_info {type:XDC file:7 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[4]}]
set_property src_info {type:XDC file:7 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[5]}]
set_property src_info {type:XDC file:7 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[6]}]
set_property src_info {type:XDC file:7 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[7]}]
set_property src_info {type:XDC file:7 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[8]}]
set_property src_info {type:XDC file:7 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[9]}]
set_property src_info {type:XDC file:7 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[10]}]
set_property src_info {type:XDC file:7 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {pixel_data[11]}]
set_property src_info {type:XDC file:7 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports h_sync]
set_property src_info {type:XDC file:7 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports v_sync]
set_property src_info {type:XDC file:7 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports sys_rst]
set_property src_info {type:XDC file:7 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {BTNX[3]}]
set_property src_info {type:XDC file:7 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {BTNX[2]}]
set_property src_info {type:XDC file:7 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {BTNX[1]}]
set_property src_info {type:XDC file:7 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {BTNX[0]}]
set_property src_info {type:XDC file:7 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {BTNY[3]}]
set_property src_info {type:XDC file:7 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {BTNY[2]}]
set_property src_info {type:XDC file:7 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {BTNY[1]}]
set_property src_info {type:XDC file:7 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {BTNY[0]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells page_config_inst/font_data]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells page_game_inst/font_data]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells page_main_inst/main_menu_data]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells page_help_inst/help_menu_data]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells page_config_inst/config_menu_data]
