# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/LDFEXP/2024Final/2024Final.srcs/sources_1/ip/blk_mem_num_font/blk_mem_num_font.xci
# IP: The module: 'blk_mem_num_font' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/LDFEXP/2024Final/2024Final.gen/sources_1/ip/blk_mem_num_font/blk_mem_num_font_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_num_font'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/LDFEXP/2024Final/2024Final.srcs/sources_1/ip/blk_mem_num_font/blk_mem_num_font.xci
# IP: The module: 'blk_mem_num_font' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/LDFEXP/2024Final/2024Final.gen/sources_1/ip/blk_mem_num_font/blk_mem_num_font_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_num_font'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
